-- GreenSoftware Database Schema Definition
-- Run this script using asyncpg python script to initialize the empty Supabase database.

-- 1. Users Extension (Assuming Clerk handles auth, we store basic profile sync)
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY, -- Mapped from Clerk User ID
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    is_premium BOOLEAN DEFAULT FALSE
);

-- 2. Homes/Properties
CREATE TABLE IF NOT EXISTS homes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id VARCHAR(255) REFERENCES users(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    timezone VARCHAR(50) DEFAULT 'UTC',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Devices/Appliances (The hardware reporting data or being controlled)
CREATE TABLE IF NOT EXISTS devices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    home_id UUID REFERENCES homes(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL, -- e.g., 'Primary Water Tank', 'Washing Machine'
    device_type VARCHAR(50) NOT NULL, -- e.g., 'SENSOR', 'ACTUATOR', 'METER'
    is_online BOOLEAN DEFAULT TRUE,
    last_ping TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Sensor Readings (Time-Series Telemetry Table)
CREATE TABLE IF NOT EXISTS sensor_readings (
    id BIGSERIAL PRIMARY KEY,
    device_id UUID REFERENCES devices(id) ON DELETE CASCADE,
    metric_type VARCHAR(50) NOT NULL, -- 'WATER_LEVEL', 'POWER_USAGE'
    value DOUBLE PRECISION NOT NULL,
    unit VARCHAR(20) NOT NULL, -- 'L', 'kWh', '%'
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- Create an index to optimize time-series slicing
CREATE INDEX IF NOT EXISTS idx_sensor_readings_device_time ON sensor_readings(device_id, timestamp DESC);

-- 5. Automation Rules (User-defined logic gates)
CREATE TABLE IF NOT EXISTS automation_rules (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id UUID REFERENCES devices(id) ON DELETE CASCADE,
    rule_type VARCHAR(50) NOT NULL, -- 'AUTO_CUTOFF', 'DRY_RUN_PROTECTION', 'ROUTE_CONDENSATE'
    is_enabled BOOLEAN DEFAULT TRUE,
    parameters JSONB, -- Stores specific logic like {"threshold_percent": 100}
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Anomalies & Alerts (Generated by ML system)
CREATE TABLE IF NOT EXISTS anomalies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id UUID REFERENCES devices(id) ON DELETE CASCADE,
    anomaly_type VARCHAR(50) NOT NULL, -- 'LEAK_DETECTED', 'UNUSUAL_POWER_SPIKE'
    severity VARCHAR(20) NOT NULL, -- 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'
    description TEXT,
    is_resolved BOOLEAN DEFAULT FALSE,
    detected_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
