ALTER TABLE homes DROP CONSTRAINT IF EXISTS homes_user_id_fkey;
ALTER TABLE users ALTER COLUMN id TYPE VARCHAR(255);
ALTER TABLE homes ALTER COLUMN user_id TYPE VARCHAR(255);
ALTER TABLE homes ADD CONSTRAINT homes_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
