from fastapi import APIRouter, Depends, HTTPException
from typing import List, Dict, Any
from uuid import UUID
from datetime import datetime, timedelta
import random

from app.core.database import db
from app.models.schemas import Home, Device, AutomationRule, Anomaly, SensorReadingCreate

router = APIRouter()

# --- 1. Dashboard KPI Summary ---
@router.get("/homes/{home_id}/dashboard-summary", response_model=Dict[str, Any])
async def get_dashboard_summary(home_id: UUID):
    """
    Returns aggregate KPIs for the Overview Dashboard.
    In a fully hydrated database, this would aggregate `sensor_readings`.
    For now, we return calculated mock structures that the frontend expects.
    """
    if not db.pool:
        raise HTTPException(status_code=503, detail="Database connection not available")
        
    async with db.pool.acquire() as conn:
        # Check if home exists
        home = await conn.fetchrow("SELECT * FROM homes WHERE id = $1", home_id)
        
        # We simulate the complex mathematical aggregates here since the DB is empty
        # but the infrastructure is now wired to query real rows later.
        
        return {
            "water_saved_liters": 1250,
            "energy_saved_kwh": 45.2,
            "system_health": 98,
            "active_devices": await conn.fetchval("SELECT COUNT(*) FROM devices WHERE home_id = $1 AND is_online = true", home_id) or 0
        }

# --- 2. Analytics & Device Metrics ---
@router.get("/devices/{device_id}/analytics")
async def get_device_analytics(device_id: UUID, days: int = 7):
    """
    Retrieves the 7-day trailing usage for a specific device,
    merging it with the ML forecasting generated by prophet_service.
    """
    if not db.pool:
        raise HTTPException(status_code=503, detail="Database connection not available")
        
    # This endpoint will query `sensor_readings` for historical data
    # and hit the ML service for predictions.
    
    # Mock response matching frontend Recharts expectation
    return {
        "device_id": device_id,
        "historical_data": [
            {"day": "Mon", "value": 450},
            {"day": "Tue", "value": 420},
            {"day": "Wed", "value": 480}
        ],
        "forecast_data": [
            {"day": "Thu", "value": 390},
            {"day": "Fri", "value": 440}
        ]
    }

# --- 3. Telemetry Ingestion ---
@router.post("/telemetry/ingest")
async def ingest_telemetry(readings: List[SensorReadingCreate]):
    """
    High-throughput endpoint for IoT hardware to post state arrays.
    """
    if not db.pool:
        raise HTTPException(status_code=503, detail="Database connection not available")
        
    async with db.pool.acquire() as conn:
        # Batch insert optimized for asyncpg
        values = [(r.device_id, "WATER_LEVEL", r.value, r.unit, r.ts) for r in readings]
        await conn.executemany('''
            INSERT INTO sensor_readings (device_id, metric_type, value, unit, timestamp)
            VALUES ($1, $2, $3, $4, $5)
        ''', values)
        
    return {"status": "success", "inserted_count": len(readings)}

# --- 4. Automations Control ---
@router.put("/automations/{rule_id}")
async def toggle_automation_rule(rule_id: UUID, is_enabled: bool):
    """
    Toggles the active state of a system automation rule.
    """
    if not db.pool:
        raise HTTPException(status_code=503, detail="Database connection not available")
        
    async with db.pool.acquire() as conn:
        result = await conn.execute(
            "UPDATE automation_rules SET is_enabled = $1, updated_at = now() WHERE id = $2",
            is_enabled, rule_id
        )
        if result == "UPDATE 0":
            raise HTTPException(status_code=404, detail="Rule not found")
            
    return {"status": "success", "rule_id": rule_id, "is_enabled": is_enabled}
